spring.application.name: employee-api
server.port: 8111
employee:
  api:
    url: http://localhost:8112/api/v1
resilience4j:
  retry:
    instances:
      employeeServiceRetry:
        max-attempts: 5
        wait-duration: 15000ms
        retry-exceptions:
          - feign.FeignException$TooManyRequests
          - feign.FeignException$InternalServerError
        enable-exponential-backoff: true
        exponential-backoff-base: 2
        exponential-backoff-max-duration: 10000ms